package artifact

import (
	"crypto/sha256"
	"fmt"
	"os"
	"path/filepath"
	"testing"
)

const testCommit = "0123456789abcdef0123456789abcdef01234567"

func fixture(t *testing.T) string {
	t.Helper()
	dir := t.TempDir()
	for _, name := range []string{"analysis", "authorizer"} {
		if err := os.Mkdir(filepath.Join(dir, name), 0o700); err != nil {
			t.Fatal(err)
		}
		wasm := []byte("\x00asm" + name)
		write(t, filepath.Join(dir, name, name+".wasm"), wasm)
		hash := fmt.Sprintf("// Code generated by scripts/build-wasm.sh. DO NOT EDIT.\n\npackage %s\n\nconst SHA256 = \"%x\"\n", name, sha256.Sum256(wasm))
		write(t, filepath.Join(dir, name, "sha256.go"), []byte(hash))
	}
	write(t, filepath.Join(dir, "SOURCE_COMMIT"), []byte(testCommit+"\n"))
	rewriteManifest(t, dir)
	return dir
}

func rewriteManifest(t *testing.T, dir string) {
	t.Helper()
	var manifest string
	for _, name := range []string{"analysis/analysis.wasm", "analysis/sha256.go", "authorizer/authorizer.wasm", "authorizer/sha256.go"} {
		data, err := os.ReadFile(filepath.Join(dir, filepath.FromSlash(name)))
		if err != nil {
			t.Fatal(err)
		}
		manifest += fmt.Sprintf("%x  %s\n", sha256.Sum256(data), name)
	}
	write(t, filepath.Join(dir, "SHA256SUMS"), []byte(manifest))
}

func write(t *testing.T, path string, data []byte) {
	t.Helper()
	if err := os.WriteFile(path, data, 0o600); err != nil {
		t.Fatal(err)
	}
}
