package artifact

import (
	"bytes"
	"fmt"
)

func verifyGoHash(source []byte, packageName, expectedHash string) error {
	expected := fmt.Sprintf("// Code generated by scripts/build-wasm.sh. DO NOT EDIT.\n\npackage %s\n\nconst SHA256 = %q\n", packageName, expectedHash)
	if !bytes.Equal(source, []byte(expected)) {
		return fmt.Errorf("SHA256 constant or generated source does not match the Wasm module")
	}
	return nil
}
