package artifact

import (
	"fmt"
	"regexp"
	"strings"
)

// LinkSource accepts library names and a digest, preventing injected Go or linker paths.
func LinkSource(platform string, flags []string, libraryDigest string) ([]byte, error) {
	parts := strings.Split(platform, "_")
	if len(parts) != 2 || len(flags) == 0 {
		return nil, fmt.Errorf("invalid native linker requirements")
	}
	if !regexp.MustCompile(`^[0-9a-f]{64}$`).MatchString(libraryDigest) {
		return nil, fmt.Errorf("invalid native library digest")
	}
	for _, flag := range flags {
		if !regexp.MustCompile(`^-l[A-Za-z0-9_]+$`).MatchString(flag) {
			return nil, fmt.Errorf("invalid native linker requirement: %s", flag)
		}
	}
	source := fmt.Sprintf("// Code generated by scripts/build-native.sh. DO NOT EDIT.\n\n//go:build %s && %s && cgo\n\npackage native\n\n// #cgo LDFLAGS: -L${SRCDIR}/lib/%s -lcgw_native %s\nimport \"C\"\n\n// LibrarySHA256 binds Go's build cache to the linked native archive.\nconst LibrarySHA256 = %q\n", parts[0], parts[1], platform, strings.Join(flags, " "), libraryDigest)
	return []byte(source), nil
}
