package artifact

import (
	"fmt"
	"regexp"
	"strings"
)

// LinkSource accepts libraries and macOS framework pairs without linker paths or injected Go text.
func LinkSource(platform string, flags []string, libraryDigest string) ([]byte, error) {
	parts := strings.Split(platform, "_")
	if len(parts) != 2 || len(flags) == 0 {
		return nil, fmt.Errorf("invalid native linker requirements")
	}
	if !regexp.MustCompile(`^[0-9a-f]{64}$`).MatchString(libraryDigest) {
		return nil, fmt.Errorf("invalid native library digest")
	}
	if err := validateLinkerFlags(platform, flags); err != nil {
		return nil, err
	}
	source := fmt.Sprintf("// Code generated by scripts/build-native.sh. DO NOT EDIT.\n\n//go:build %s && %s && cgo\n\npackage native\n\n// #cgo LDFLAGS: -L${SRCDIR}/lib/%s -lcgw_native %s\nimport \"C\"\n\n// LibrarySHA256 binds Go's build cache to the linked native archive.\nconst LibrarySHA256 = %q\n", parts[0], parts[1], platform, strings.Join(flags, " "), libraryDigest)
	return []byte(source), nil
}

func validateLinkerFlags(platform string, flags []string) error {
	for index := 0; index < len(flags); index++ {
		flag := flags[index]
		if flag != "-framework" {
			if !regexp.MustCompile(`^-l[A-Za-z0-9_]+$`).MatchString(flag) {
				return fmt.Errorf("invalid native linker requirement: %s", flag)
			}
			continue
		}
		if platform != "darwin_arm64" {
			return fmt.Errorf("native frameworks require darwin_arm64")
		}
		index++
		if index == len(flags) {
			return fmt.Errorf("native framework has no name")
		}
		if !regexp.MustCompile(`^[A-Za-z0-9_]+$`).MatchString(flags[index]) {
			return fmt.Errorf("invalid native framework name: %s", flags[index])
		}
	}
	return nil
}
