// Code generated by scripts/build-wasm.sh. DO NOT EDIT.

package analysis

// SHA256 is the hex SHA-256 of analysis.wasm.
const SHA256 = "1c2a578d7368ee887af47bdd8e25535fd39f7c18b2c8cd952fe7ec06f66b029d"
