#!/usr/bin/env bash
# Build both guests with the pinned toolchain and write their integrity records.
set -euo pipefail

repo=$(cd "$(dirname "$0")/.." && pwd)
cargo_home=$(cd "${CARGO_HOME:-$HOME/.cargo}" && pwd)
rustup_home=$(cd "${RUSTUP_HOME:-$HOME/.rustup}" && pwd)
toolchain=$(sed -n 's/^channel = "\([^"]*\)"$/\1/p' "$repo/rust-toolchain.toml")
[[ -n "$toolchain" ]] || { echo "missing pinned Rust toolchain" >&2; exit 1; }
mkdir -p "${CARGO_TARGET_DIR:-$repo/rust/target}" "${WASM_OUTPUT_DIR:-$repo/internal/modules}"
export CARGO_TARGET_DIR=$(cd "${CARGO_TARGET_DIR:-$repo/rust/target}" && pwd)
output=$(cd "${WASM_OUTPUT_DIR:-$repo/internal/modules}" && pwd)

# An 8 MiB stack matches native Linux's default; placing it below data makes overflow trap.
# Generated Cedar parsers embed their source paths, so remap the target directory too.
export RUSTFLAGS="-C link-arg=-zstack-size=8388608 --remap-path-prefix=$repo=/cedar-go-wasm --remap-path-prefix=$cargo_home=/cargo --remap-path-prefix=$rustup_home=/rustup --remap-path-prefix=$CARGO_TARGET_DIR=/cedar-target"
export CARGO_INCREMENTAL=0
unset CARGO_BUILD_RUSTFLAGS CARGO_ENCODED_RUSTFLAGS RUSTC RUSTC_WRAPPER RUSTC_WORKSPACE_WRAPPER

"$repo/scripts/vendor-symcc.sh"
cd "$repo/rust"
cargo +"$toolchain" build --locked --release --target wasm32-wasip1 -p cgw-authorizer -p cgw-analysis

install_module() {
	local crate=$1 name=$2
	local dir="$output/$name"
	mkdir -p "$dir"
	cp "$CARGO_TARGET_DIR/wasm32-wasip1/release/$crate.wasm" "$dir/$name.wasm"
	local sum
	sum=$(sha256sum "$dir/$name.wasm" | cut -d' ' -f1)
	cat >"$dir/sha256.go" <<EOF
// Code generated by scripts/build-wasm.sh. DO NOT EDIT.

package $name

const SHA256 = "$sum"
EOF
	echo "$name.wasm $sum $(stat -c %s "$dir/$name.wasm") bytes"
}

install_module cgw_authorizer authorizer
install_module cgw_analysis analysis

cd "$output"
sha256sum analysis/analysis.wasm analysis/sha256.go authorizer/authorizer.wasm authorizer/sha256.go > SHA256SUMS
git -C "$repo" rev-parse HEAD > SOURCE_COMMIT
