#!/usr/bin/env bash
# CI rebuilds the embedded modules and hashes to verify the committed artifacts.
set -euo pipefail

repo=$(cd "$(dirname "$0")/.." && pwd)
cargo_home=$(cd "${CARGO_HOME:-$HOME/.cargo}" && pwd)
rustup_home=$(cd "${RUSTUP_HOME:-$HOME/.rustup}" && pwd)

# An 8 MiB stack matches native Linux's default; placing it below data makes overflow trap.
# Path remapping keeps checkout and toolchain locations out of reproducible artifacts.
export RUSTFLAGS="-C link-arg=-zstack-size=8388608 --remap-path-prefix=$repo=/cedar-go-wasm --remap-path-prefix=$cargo_home=/cargo --remap-path-prefix=$rustup_home=/rustup"
export CARGO_INCREMENTAL=0
unset CARGO_BUILD_RUSTFLAGS CARGO_ENCODED_RUSTFLAGS RUSTC_WRAPPER

cd "$repo/rust"
cargo build --locked --release --target wasm32-wasip1 -p cgw-authorizer -p cgw-analysis

install_module() {
	local crate=$1 name=$2
	local dir="$repo/internal/modules/$name"
	cp "target/wasm32-wasip1/release/$crate.wasm" "$dir/$name.wasm"
	local sum
	sum=$(sha256sum "$dir/$name.wasm" | cut -d' ' -f1)
	cat >"$dir/sha256.go" <<EOF
// Code generated by scripts/build-wasm.sh. DO NOT EDIT.

package $name

const SHA256 = "$sum"
EOF
	echo "$name.wasm $sum $(stat -c %s "$dir/$name.wasm") bytes"
}

install_module cgw_authorizer authorizer
install_module cgw_analysis analysis
