#!/usr/bin/env bash
# Native fixtures are generated by direct pinned cedar-policy calls, independent of the guest.
set -euo pipefail
repo=$(cd "$(dirname "$0")/.." && pwd)
actual=$(mktemp)
trap 'rm -f "$actual"' EXIT
cd "$repo/rust"
cargo run --locked --release -p cgw-verification --bin template_fixtures > "$actual"
diff -u "$repo/testdata/parity/templates/native.json" "$actual"
cd "$repo"
go test -count=1 -run '^TestTemplateNativeParity$' ./cedar/policy/template
