"""Generate linker source from ordered, validated native requirements."""

import re


def validate_flags(platform, flags):
    if not isinstance(flags, list) or not flags:
        raise ValueError("invalid native linker requirements")
    index = 0
    while index < len(flags):
        flag = flags[index]
        if flag != "-framework":
            if not isinstance(flag, str) or not re.fullmatch(r"-l[A-Za-z0-9_]+", flag):
                raise ValueError(f"invalid native linker requirement: {flag}")
            index += 1
            continue
        if platform != "darwin_arm64":
            raise ValueError("native frameworks require darwin_arm64")
        index += 1
        if index == len(flags):
            raise ValueError("native framework has no name")
        name = flags[index]
        if not isinstance(name, str) or not re.fullmatch(r"[A-Za-z0-9_]+", name):
            raise ValueError(f"invalid native framework name: {name}")
        index += 1


def link_source(platform, flags, library_digest):
    parts = platform.split("_")
    if len(parts) != 2:
        raise ValueError("invalid native linker requirements")
    if not isinstance(library_digest, str) or not re.fullmatch(r"[0-9a-f]{64}", library_digest):
        raise ValueError("invalid native library digest")
    validate_flags(platform, flags)
    os_name, arch = parts
    return (
        "// Code generated by scripts/build-native.sh. DO NOT EDIT.\n\n"
        f"//go:build {os_name} && {arch} && cgo\n\npackage native\n\n"
        f"// #cgo LDFLAGS: -L${{SRCDIR}}/lib/{platform} -lcgw_native {' '.join(flags)}\n"
        'import "C"\n'
        "\n// LibrarySHA256 binds Go's build cache to the linked native archive.\n"
        f'const LibrarySHA256 = "{library_digest}"\n'
    ).encode()
