// Code generated by scripts/build-wasm.sh. DO NOT EDIT.

package authorizer

// SHA256 is the hex SHA-256 of authorizer.wasm.
const SHA256 = "db59bcba4142504279f579e85cee05b8cec419367c1539a233940bc74253b5b9"
